language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-dev libsqlite3-dev

script:
  - mkdir tests/build
  - mkdir build
  - cd tests/build
  - cmake ..
  - make
  - ./sqlb-unittests
  - cd ../../build
  - cmake ..
  - make

matrix:
  fast_finish: true
